### ISSUE TITLE
Compile image in `Fedora release 35 (Thirty Five)` and error happened

### ISSUE THREAD

**Issue by dxsup** [CloudDectective-Harmonycloud/kindling#353]
I compile image in `Fedora release 35 (Thirty Five)` and err following

```
+ docker run -it -v /usr:/host/usr -v /lib/modules:/host/lib/modules -v /tmp/rebuild-kindling-agent/agent-libs-76a5bf0c4f7f37eda359895fc3f9b62a6bb4cb05:/source kindlingproject/kernel-builder:latest
Compile probe for 5.14.10-300.fc35.x86_64
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=/source/driver modules
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
  CC [M]  /source/driver/main.o
scripts/basic/fixdep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by scripts/basic/fixdep)
scripts/basic/fixdep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by scripts/basic/fixdep)
make[2]: *** [scripts/Makefile.build:271: /source/driver/main.o] Error 1
make[2]: *** Deleting file '/source/driver/main.o'
make[1]: *** [Makefile:1858: /source/driver] Error 2
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make: *** [Makefile:17: all] Error 2
mv: cannot stat 'kindling-falcolib-probe.ko': No such file or directory
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=/source/driver clean
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
5.14.10-300.fc35.x86_64
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=$PWD
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
clang -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi-I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h \
	 -D__KERNEL__   \
	 \
	 \
	-DCPU_ANALYSIS \
	-D__KERNEL__ \
	-D__BPF_TRACING__ \
	-Wno-gnu-variable-sized-type-not-at-end \
	-Wno-address-of-packed-member \
	-fno-jump-tables \
	-fno-stack-protector \
	-Wno-tautological-compare \
	-O2 -g -emit-llvm -c /source/driver/bpf/probe.c -o /source/driver/bpf/probe.ll
/source/driver/bpf/probe.c:225:16: error: no member named 'state' in 'struct task_struct'
                if (_READ(p->state) == TASK_RUNNING) {
                          ~  ^
/source/driver/bpf/plumbing_helpers.h:20:28: note: expanded from macro '_READ'
#define _READ(P) ({ typeof(P) _val;                             \
                           ^
/source/driver/bpf/probe.c:225:16: error: no member named 'state' in 'struct task_struct'
                if (_READ(p->state) == TASK_RUNNING) {
                          ~  ^
/source/driver/bpf/plumbing_helpers.h:22:44: note: expanded from macro '_READ'
                    bpf_probe_read(&_val, sizeof(_val), &P);    \
                                                         ^
/source/driver/bpf/probe.c:225:23: error: invalid operands to binary expression ('void' and 'int')
                if (_READ(p->state) == TASK_RUNNING) {
                    ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
3 errors generated.
make[2]: *** [/source/driver/bpf/Makefile:40: /source/driver/bpf/probe.o] Error 1
make[1]: *** [Makefile:1858: /source/driver/bpf] Error 2
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make: *** [Makefile:25: all] Error 2
mv: cannot stat 'probe.o': No such file or directory
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=$PWD clean
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
compile-probe.sh: line 20: cd: bpf: No such file or directory
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=$PWD
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
clang -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi-I./include/uapi -I./include/generated/uapi -include ./include/linux/compiler-version.h -include ./include/linux/kconfig.h \
	 -D__KERNEL__   \
	 \
	 \
	-DCPU_ANALYSIS \
	-D__KERNEL__ \
	-D__BPF_TRACING__ \
	-Wno-gnu-variable-sized-type-not-at-end \
	-Wno-address-of-packed-member \
	-fno-jump-tables \
	-fno-stack-protector \
	-Wno-tautological-compare \
	-O2 -g -emit-llvm -c /source/driver/bpf/probe.c -o /source/driver/bpf/probe.ll
/source/driver/bpf/probe.c:225:16: error: no member named 'state' in 'struct task_struct'
                if (_READ(p->state) == TASK_RUNNING) {
                          ~  ^
/source/driver/bpf/plumbing_helpers.h:20:28: note: expanded from macro '_READ'
#define _READ(P) ({ typeof(P) _val;                             \
                           ^
/source/driver/bpf/probe.c:225:16: error: no member named 'state' in 'struct task_struct'
                if (_READ(p->state) == TASK_RUNNING) {
                          ~  ^
/source/driver/bpf/plumbing_helpers.h:22:44: note: expanded from macro '_READ'
                    bpf_probe_read(&_val, sizeof(_val), &P);    \
                                                         ^
/source/driver/bpf/probe.c:225:23: error: invalid operands to binary expression ('void' and 'int')
                if (_READ(p->state) == TASK_RUNNING) {
                    ~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
3 errors generated.
make[2]: *** [/source/driver/bpf/Makefile:40: /source/driver/bpf/probe.o] Error 1
make[1]: *** [Makefile:1858: /source/driver/bpf] Error 2
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make: *** [Makefile:25: all] Error 2
mv: cannot stat 'probe.o': No such file or directory
make -C /lib/modules/5.14.10-300.fc35.x86_64/build M=$PWD clean
make[1]: Entering directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
make[1]: Leaving directory '/host/usr/src/kernels/5.14.10-300.fc35.x86_64'
```

_Originally posted by @yehaifeng in https://github.com/CloudDectective-Harmonycloud/kindling/issues/106#issuecomment-1313371231_

**Comment by dxsup** [comment]
@yehaifeng We can talk about this problem in this issue.

**Comment by yehaifeng** [comment]
So now i compile agent to support my kernel, but another error occur
```
* Mounting debugfs
* BPF probe located, it's now possible to start kindling
* Load probe succeeded, and will create /opt/kernel-support for kubernetes
2022/11/15 05:28:06 GitCommitInfo:; go1.17.12 linux/amd64
2022-11-15T05:28:06.972Z	INFO	component/telemetry.go:48	Log Initialize Success! ConsoleLevel: info,FileRotationLevel: info
FileRotationConfig: 	LogFile: agent.log	MaxSize: 512m	backup: 5	MaxAge: 30day
2022-11-15T05:28:06.972Z	INFO	component/telemetry.go:58	[CLUSTER_ID] is not found in env variable which will be set [noclusteridset]
2022-11-15T05:28:06.972Z	INFO	observability/telemetry.go:157	Initializing self-observability exporter whose type is stdout
2022-11-15T05:28:06.974Z	WARN	otelexporter/otelexporter.go:104	[CLUSTER_ID] is not found in env variable which willbe set [noclusteridset]
2022-11-15T05:28:06.976Z	INFO	otelexporter/prometheus.go:18	Prometheus Server listening at port: [:9500]
2022-11-15T05:28:06.976Z	PANIC	k8sprocessor/kubernetes_processor.go:50	Failed to initialize [k8smetadataprocessor]: cannot connect to kubernetes: error connecting to k8s with auth_type=kubeConfig: stat /root/.kube/config: no such file or directory. Set theoption 'enable' false if you want to run the agent in the non-Kubernetes environment.
panic: Failed to initialize [k8smetadataprocessor]: cannot connect to kubernetes: error connecting to k8s with auth_type=kubeConfig:stat /root/.kube/config: no such file or directory. Set the option 'enable' false if you want to run the agent in the non-Kubernetesenvironment.

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000437a40, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*SugaredLogger).log(0xc00069fb58, 0x4, {0x1b7fc16, 0x7f4c6238c200}, {0xc0002dfb38, 0x7f4c6254bfff, 0x10000c0002dfaa0}, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/root/go/pkg/mod/go.uber.org/zap@v1.19.1/sugar.go:159
github.com/Kindling-project/kindling/collector/pkg/component.(*TelemetryLogger).Panicf(...)
	/kindling/collector/pkg/component/telemetry.go:166
github.com/Kindling-project/kindling/collector/pkg/component/consumer/processor/k8sprocessor.NewKubernetesProcessor({0x173e060, 0x2d43ec0}, 0xc0007455c0, {0x7f4c6002f278, 0xc0007682d0})
	/kindling/collector/pkg/component/consumer/processor/k8sprocessor/kubernetes_processor.go:50 +0x4f7
github.com/Kindling-project/kindling/collector/internal/application.(*Application).buildPipeline(0xc0006a3980)
	/kindling/collector/internal/application/application.go:123 +0x2d8
github.com/Kindling-project/kindling/collector/internal/application.New()
	/kindling/collector/internal/application/application.go:52 +0x4f4
main.main()
	/kindling/collector/cmd/kindling-collector/main.go:21 +0x6a
```

**Comment by dxsup** [comment]
You can disable the Kubernetes connection by setting the option 'enable' to false if you want to run the agent in the non-Kubernetes environment.
```yaml
processors:
  k8smetadataprocessor:
    # Set "enable" false if you want to run the agent in the non-Kubernetes environment.
    # Otherwise, the agent will panic if it can't connect to the API-server.
    enable: true
```

**Comment by yehaifeng** [comment]
My env is openshift4

**Comment by dxsup** [comment]
Are you running the agent in Kubernetes? Could you attach your configuration file?

**Comment by dxsup** [comment]
We have talked about this issue in the WeChat Group. You used the old deployment yaml file that mounts the configuration file to `/etc/kindling/config/`. But the latest version requests it at `/app/config`.

**Comment by dxsup** [comment]
And the compiling error can be fixed by replacing `state` with `__state`. This is a compatibility issue with Fedora. We will fix it later.
